#!/bin/bash
# guac-list.sh
# jsp2205, 2020
# Columbia University, Zuckerman Research Computing
#
# This script will output URIs for all active VNC sessions that can be used with Guacamole.
#
# See here for more details: https://guacamole.apache.org/doc/gug/adhoc-connections.html#using-quickconnect
shopt -s nullglob

GUACVNCDIR=${HOME}/.guacvnc

# Create a hash to group VNC sessios by host.
declare -A GUACVNCURIS
declare -A GUACVNCDISPLAYNUMS
declare -A GUACVNCSESSIONHOSTIDX
for PIDFILE in ${GUACVNCDIR}/*.pid;
do
	HOST=$(basename -s .pid ${PIDFILE} | cut -d: -f1)
	# Make sure index is initialized and set to 1 (we're using 1-indexing for end-user readability)
	[ -z "${GUACVNCSESSIONHOSTIDX[${HOST}]}" ] && GUACVNCSESSIONHOSTIDX[${HOST}]=1
	DISPLAYNUM=$(basename -s .pid ${PIDFILE} | cut -d: -f2)
	GUACVNCPORT="59$(printf '%02d' ${DISPLAYNUM})"
	GUACVNCPASSWDCLEAR="${GUACVNCDIR}/.${HOST}:${DISPLAYNUM}-passwd-clear"
	GUACVNCPASSWD=$(cat ${GUACVNCPASSWDCLEAR})
	IDX=${GUACVNCSESSIONHOSTIDX[${HOST}]}
	GUACVNCURIS[${HOST}_${IDX}]="vnc://$(whoami):${GUACVNCPASSWD}@${HOST}:${GUACVNCPORT}"
	GUACVNCDISPLAYNUMS[${HOST}_${IDX}]=${DISPLAYNUM}
	GUACVNCSESSIONHOSTIDX[${HOST}]=$(( ${IDX} + 1 ))
done

for HOST in ${!GUACVNCSESSIONHOSTIDX[@]};
do
	IDX=1
	echo -e "Active VNC Connections for ${HOST}:\n"
	HOSTLEN=$(echo ${HOST} | wc -c)
	printf "%-3s %-33s %-${HOSTLEN}s %-2s\n" "" "URI" "Host" "Display Number"
	while [ ${IDX} -ne ${GUACVNCSESSIONHOSTIDX[${HOST}]} ];
	do
		GUACURI=${GUACVNCURIS["${HOST}_${IDX}"]}
		GUACDISPLAYNUM=${GUACVNCDISPLAYNUMS["${HOST}_${IDX}"]}
		printf "%-3s %-33s %-${HOSTLEN}s %-2s\n" "${IDX}." ${GUACURI} ${HOST} ${GUACDISPLAYNUM}
		IDX=$(( ${IDX} + 1 ))
	done
	echo
done
